tags:
  db: true

replicaCount: 1

image:
  repository: containerum/user
  tag: v1.0.0
  pullPolicy: Always
  secret:

service:
  port: 8111
  targetPort: 8111
  externalIP:

env:
  GIN_MODE: debug
  CH_USER_LOG_LEVEL: 5
  CH_USER_DB: "usermanager"
  CH_USER_PG_LOGIN: "usermanager"
  CH_USER_PG_PASSWORD: "ae9Oodai3aid"
  CH_USER_PG_ADDR: "postgres:5432"
  CH_USER_PG_DBNAME: "usermanager"
  CH_USER_PG_NOSSL: true
  CH_USER_PG_URL:
  CH_USER_MIGRATIONS_PATH: "migrations"
  CH_USER_MAIL: "http"
  CH_USER_MAIL_URL: "http://ch-mail-templater:7070/"
  CH_USER_RECAPTCHA: "dummy"
  CH_USER_RECAPTCHA_KEY: "recaptcha_key"
  CH_USER_OAUTH_CLIENTS: "http"
  CH_USER_AUTH_GRPC_ADDR: "ch-auth:1112"
  CH_USER_RESOURCE_SERVICE: "http"
  CH_USER_RESOURCE_SERVICE_URL: "http://resource-service:1213"
  CH_USER_LISTEN_ADDR: ":8111"
  CH_USER_USER_MANAGER: "impl"

postgresql:
  persistence:
    enabled: false
  postgresUser: user
  postgresDatabase: user
  postgresPassword: password
